Practice Code Review - DO NOT MERGE!
Decatur-Robotics/Common-Library-And-Wiki pull request #37
Opened 2023-11-30 22:44 UTC by renatodellosso

2023-12-12 22:48 UTC, Tr01ler requested changes
Elevator motor main is not final

2023-12-12 22:50 UTC, seankid commented on RobotCode/src/main/java/frc/robot/Ports.java
> +    public static int ELEVATOR_MOTOR_MAIN = 0;
something is messed up here its either missing final designation or is incorrectly named

2023-12-14 21:21 UTC, seankid commented on RobotCode/src/main/java/frc/robot/RobotContainer.java
> +	public final static ShuffleboardTab shuffleboard = Shuffleboard.getTab("Tab 1");
idk something seems off here i cant place my finger on it

2023-12-14 21:37 UTC, PPenguin1 reviewed
Public static double ELEVATOR_DEADBAND_VALUE to elevatorDeadbandValue

2023-12-14 21:37 UTC, PPenguin1 commented on RobotCode/src/main/java/frc/robot/Ports.java
> +    public static int ELEVATOR_MOTOR_MAIN = 0;
elevatorMotorMain

2023-12-14 21:37 UTC, PPenguin1 commented on RobotCode/src/main/java/frc/robot/commands/MoveElevatorCommand.java
> +	public DoubleSupplier input;
doubleSupplier

2023-12-14 21:37 UTC, PPenguin1 commented on RobotCode/src/main/java/frc/robot/commands/MoveElevatorCommand.java
> +	public ElevatorSubsystem elevator;
elevatorSubsystem

2023-12-14 21:37 UTC, PPenguin1 commented on RobotCode/src/main/java/frc/robot/subsystems/ClawIntakeSubsystem.java
> +	public DoubleSolenoid clawGrabberLeft, clawGrabberRight;
doubleSolenoid

2023-12-14 21:37 UTC, PPenguin1 commented on RobotCode/src/main/java/frc/robot/subsystems/ElevatorSubsystem.java
> +	static AnalogPotentiometer potentiometer;
analogPotentiometer

2023-12-14 21:37 UTC, PPenguin1 commented on RobotCode/src/main/java/frc/robot/subsystems/ElevatorSubsystem.java
> +	static ClawIntakeSubsystem intake;
clawIntakeSubsystem

2023-12-14 21:39 UTC, seankid reviewed
several things are mid

2023-12-14 21:39 UTC, seankid commented on RobotCode/src/main/java/frc/robot/constants/Constants.java
> +	public final int ELEVATOR_MAX_POWER_CHANGE = 0;
Should be named differently

2023-12-14 21:47 UTC, li46554 commented on RobotCode/src/main/java/frc/robot/subsystems/ElevatorSubsystem.java
> +		} // /jack morton lawrence torrance jack morton lawrence torrance jack morton
silly comment

2024-12-04 20:53 UTC, closed without merging